### ISSUE TITLE
Keep activities source code and deployment files in public repository

### ISSUE THREAD

**Issue by gabrielmocanu** [security-summer-school/template-internal#7]
Right now we keep source code and deployment files for activities that are used during the session in our private session, but this might be an issue for the @security-summer-school/binary-track because should generate a binary and place it in the `public` folder from the public repository.

Please address an opinion related to this aspect and which you think is the best solution.

CC: @security-summer-school/web-track @security-summer-school/binary-track @security-summer-school/essentials-track

**Comment by razvand** [comment]
As discussed on Discord, I think the best course of action is to move all activities (including reference solutions) in the public repository.
